-- CreateTable
CREATE TABLE "Birthday" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "slackUser" STRING NOT NULL,
    "birthday" DATE NOT NULL,

    CONSTRAINT "Birthday_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Birthday_slackUser_key" ON "Birthday"("slackUser");
