-- CreateTable
CREATE TABLE "Birthday" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user" STRING NOT NULL,
    "birthday" DATE NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Birthday_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Birthday_user_key" ON "Birthday"("user");